* dgp_nonbuyers.do -- the data-generating process of the note's Monte Carlo
* for the correction of the non-buyers (equaids 1.1.0 and later). Defines the program
*
*   _dgp_nonbuyers N rho b1 b2 seed
*
* which replaces the data in memory by N households of an AIDS with three
* goods, generated by the model of Shonkwiler and Yen (1999):
*
*   - prices: log prices with a common shock per group of 25 households
*     (grp, sd 0.3) and a household deviation (sd 0.05);
*   - log expenditure N(1, 0.5); a count demographic hs = 1..10 entering by
*     Ray's scaling, m0 = 1 + rho hs;
*   - shares of the model: alpha = (0.20, 0.18, 0.62), Gamma symmetric with
*     rows summing to zero, beta = (b1, b2, -b1-b2), alpha_0 = 0;
*   - purchase of goods 1 and 2: probits on (1, ln(p/x), hs) and a variable
*     of the probit only (q1, q2, coefficient 1: pseudo-R2 about 0.29);
*   - shares of the buyers: f_i + e_i, e_i = 0.02 (rho_i u_i + ...), so that
*     E[w_i] = Phi f_i + delta_i phi with delta = (-0.012, 0.008); good 3
*     closes the budget;
*   - the non-buyers of goods 1 and 2 have no price (unit values), filled in
*     the estimation by pimpute(grp).
*
* The note uses rho = 0.3, b1 = -0.10, b2 = 0.08 (every parameter strongly
* identified: t of rho about 16) and, to show weak identification, rho = 0.1,
* b1 = -0.03, b2 = 0.02 (t of rho about 3).
capture program drop _dgp_nonbuyers
program define _dgp_nonbuyers
    args N rho b1 b2 seed
    clear
    quietly set obs `N'
    set seed `seed'
    quietly {
        gen int grp = ceil(_n / 25)
        gen double lx  = rnormal(1, 0.5)
        forvalues j = 1/3 {
            gen double g`j' = .
            bysort grp: replace g`j' = rnormal(0, 0.3) if _n == 1
            by grp: replace g`j' = g`j'[1]
            gen double lp`j' = g`j' + rnormal(0, 0.05)
            gen double p`j'  = exp(lp`j')
        }
        gen double x  = exp(lx)
        gen byte   hs = 1 + floor(10 * runiform())
        gen double q1 = rnormal()
        gen double q2 = rnormal()
        gen double lna = 0.20*lp1 + 0.18*lp2 + 0.62*lp3 + 0.5*(0.05*lp1^2 + 0.04*lp2^2 + 0.05*lp3^2 ///
            + 2*(-0.02)*lp1*lp2 + 2*(-0.03)*lp1*lp3 + 2*(-0.02)*lp2*lp3)
        gen double l  = lx - ln(1 + `rho'*hs) - lna
        gen double f1 = 0.20 + 0.05*lp1 - 0.02*lp2 - 0.03*lp3 + (`b1')*l
        gen double f2 = 0.18 - 0.02*lp1 + 0.04*lp2 - 0.02*lp3 + (`b2')*l
        gen double s1 = 0.5 - 0.4*(lp1 - lx) + 0.2*(lp2 - lx) + 0.1*(lp3 - lx) + 0.05*hs + q1
        gen double s2 = 0.2 + 0.1*(lp1 - lx) - 0.5*(lp2 - lx) + 0.2*(lp3 - lx) - 0.05*hs + q2
        gen double u1 = rnormal()
        gen double u2 = rnormal()
        gen double w1 = (s1 + u1 > 0) * max(f1 + 0.02*(-0.6*u1 + 0.8*rnormal()), 1e-6)
        gen double w2 = (s2 + u2 > 0) * max(f2 + 0.02*( 0.4*u2 + sqrt(0.84)*rnormal()), 1e-6)
        gen double w3 = 1 - w1 - w2
        replace p1 = . if w1 == 0
        replace p2 = . if w2 == 0
    }
end
